//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public int pages_count { get; set; }
        public int author_author_id { get; set; }
        public int language_language_id { get; set; }
    
        public virtual author author { get; set; }
        public virtual language language { get; set; }
    }
}
